
%.img: chroot-%
	$(SUDO) ./scripts/convert-chroot-to-image.sh $< $@

%.box: chroot-%-vagrant
	$(SUDO) ./scripts/convert-chroot-to-image.sh $< $@
	/usr/share/doc/vagrant-libvirt/examples/create_box.sh $< $@

chroot-%-vagrant: chroot-%
	$(SUDO) rsync -avh $</* $@
	$(SUDO) chroot $@ /usr/local/sbin/docker-upgrade
	$(SUDO) chroot $@ apt-get --assume-yes install cloud-init
	$(SUDO) chroot $@ /usr/local/sbin/docker-cleanup
	$(SUDO) cp data/cloud.yml $@/etc/cloud/cloud.cfg.d/vagrant.cfg
