
%.img: chroot-%
	$(SUDO) ./scripts/convert-chroot-to-image.sh $< $@

%.box: chroot-%-vagrant
	$(SUDO) ./scripts/convert-chroot-to-image.sh $< $@
	/usr/share/doc/vagrant-libvirt/examples/create_box.sh $< $@

chroot-%-vagrant: chroot-%
	$(SUDO) rsync -avh $< $@
	$(SUDO) cp scripts/provision-vagrant.sh $@/tmp/setup.sh
	$(SUDO) chmod +x $@/tmp/setup.sh
	$(SUDO) chroot $@ /tmp/setup.sh
	$(SUDO) rm -f $@/tmp/setup.sh
